version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm install xlsx file-saver --save
  build:
    commands: 
      - npm run build
artifacts:
    files:
      - '**/*'
    base-directory: build
